package com.twd.SpringSecurityJWT.bean.master;

import java.sql.Timestamp;

import com.twd.SpringSecurityJWT.bean.GlobalBean;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * GbltUserLogId generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
public class GenderBean extends GlobalBean {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private String gstrGenderCode;

	private String gstrGenderName;

	private Integer gnumSeatId;

	private Timestamp gdtEntryDate;

	private Integer gnumIsValid;

	private Integer gnumLastModifiedSeatId;

	private Timestamp gdtLastModifiedDate;
}
