package com.twd.SpringSecurityJWT.bean.master;

import java.sql.Timestamp;

import com.twd.SpringSecurityJWT.bean.GlobalBean;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * GbltUserLogId generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
public class NationalityBean extends GlobalBean {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private Integer gnumNationalityCode;

	private String gstrNationalityName;

	private String gstrCountryCode;

	private Integer gnumSeatId;

	private Timestamp gdtEntry;

	private Integer gnumIsValid;

	private String strRemarks;
}
