package com.twd.SpringSecurityJWT.bean.master;

// Generated Jan 29, 2018 4:01:44 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import com.twd.SpringSecurityJWT.bean.GlobalBean;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * GbltUserLogId generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
public class SuffixBean extends GlobalBean {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;

	private Integer gnumSuffixCode;

	private String gstrSuffixName;

	private Integer gnumIsValid;

	private Integer gnumSeatId;

	private Date gdtEntryDate;

	private Date gdtLstmodDate;

	private Integer gnumLstmodSeatid;

}
