package com.twd.SpringSecurityJWT.entity;
// Generated 1 Oct, 2018 4:11:17 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * GbltLoginUnsucessfulLogId generated by hbm2java
 */
@Data
@Entity
@Table(name = "gblt_login_unsucessful_log", schema = "ahiscl")
@IdClass(GbltLoginUnsucessfulLogPK.class)
public class GbltLoginUnsucessfulLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "gstr_loginid", length = 20)
	private String gstrLoginid;

	@Id
	@Column(name = "gdt_entry_date", length = 29)
	private Date gdtEntryDate;

	@Column(name = "gnum_isvalid", precision = 1, scale = 0)
	private Integer gnumIsvalid;

	@Column(name = "gstr_ip_number", length = 16)
	private String gstrIpNumber;

	@Column(name = "gnum_lock_status", precision = 1, scale = 0)
	private Integer gnumLockStatus;

}
