package com.twd.SpringSecurityJWT.entity;
// Generated 1 Oct, 2018 4:11:17 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * GbltLoginUnsucessfulLogId generated by hbm2java
 */
@Setter
@Getter
@Entity
@EqualsAndHashCode
public class GbltLoginUnsucessfulLogPK implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "gstr_loginid", length = 20)
	private String gstrLoginid;

	@Id
	@Column(name = "gdt_entry_date", length = 29)
	private Date gdtEntryDate;

}
