package com.twd.SpringSecurityJWT.entity;

// Generated Jan 29, 2018 4:01:44 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * GbltUserLogId generated by hbm2java
 */

@Setter
@Getter
@Entity
@EqualsAndHashCode
public class GbltUserLogPK implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "gdt_login_date", nullable = false, length = 29)
	private Date gdtLoginDate;

	@Id
	@Column(name = "gnum_hospital_code", nullable = false)
	private Integer gnumHospitalCode;

	@Id
	@Column(name = "gnum_seat_id", nullable = false)
	private Integer gnumSeatId;

	@Id
	@Column(name = "gnum_userid", nullable = false)
	private Integer gnumUserid;

}
