package com.twd.SpringSecurityJWT.entity.master;
// Generated 1 Oct, 2018 4:11:17 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * UmmtUserMst generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "gblt_seat_role_mst", schema = "ahiscl")
@IdClass(GbltSeatRolePKMst.class)
public class GbltSeatRoleMst implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "gnum_role_id", nullable = false)
	private Integer gnumRoleId;

	@Id
	@Column(name = "gnum_module_id", nullable = false)
	private Integer gnumModuleId;

	@Id
	@Column(name = "gnum_seatid", nullable = false)
	private Integer gnumSeatid;

	@Id
	@Column(name = "gnum_seat_role_slno", nullable = false)
	private Integer gnumSeatRoleSlno;

	@Id
	@Column(name = "gnum_hospital_code", nullable = false)
	private Integer gnumHospitalCode;

	@Column(name = "gbl_isvalid", nullable = false)
	private Integer gblIsvalid;

	@Column(name = "gnum_seat_id", nullable = false)
	private Integer gnumSeatId;

	@Column(name = "gdt_entry_date", nullable = false)
	private Date gdtEntryDate;

	@Column(name = "gdt_effective_frm")
	private Date gdtEffectiveFrm;

	@Column(name = "gdt_effective_to")
	private Date gdtEffectiveTo;

}
