package com.twd.SpringSecurityJWT.entity.master;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * GbltUserLogId generated by hbm2java
 */

@Setter
@Getter
@Entity
@EqualsAndHashCode
public class GbltSeatRolePKMst implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "gnum_role_id", nullable = false)
	private Integer gnumRoleId;

	@Id
	@Column(name = "gnum_module_id", nullable = false)
	private Integer gnumModuleId;

	@Id
	@Column(name = "gnum_seatid", nullable = false)
	private Integer gnumSeatid;

	@Id
	@Column(name = "gnum_seat_role_slno", nullable = false)
	private Integer gnumSeatRoleSlno;

	@Id
	@Column(name = "gnum_hospital_code", nullable = false)
	private Integer gnumHospitalCode;

	@Column(name = "gbl_isvalid", nullable = false)
	private Integer gblIsvalid;

}
