package com.twd.SpringSecurityJWT.entity.master;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * UmmtUserMst generated by hbm2java
 */
@Setter
@Getter
@Entity
@EqualsAndHashCode
public class GbltUserPKMst implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "gnum_userid")
	private Integer gnumUserId;

	@Id
	@Column(name = "gnum_isvalid", nullable = false)
	private Integer gnumIsValid;
}
