package com.twd.SpringSecurityJWT.entity.master;
// Generated 1 Oct, 2018 4:11:17 PM by Hibernate Tools 5.2.3.Final

import java.sql.Timestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * UmmtUserMst generated by hbm2java
 */
@Data
@Entity
@Table(name = "gblt_menu_mst", schema = "ahiscl")
public class GbltMenuMst implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column(name = "gnum_parent_id")
	private Long gnumParentId;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "gnum_menu_id")
	private Long gnumMenuId;

	@Column(name = "gstr_menu_name", nullable = false, length = 50)
	private String gstMenuName;

	@Column(name = "gstr_menuclass_id")
	private Character gstMenuClassId;

	@Column(name = "gnum_menu_level")
	private Integer gnumMenuLevel;

	@Column(name = "gnum_display_order")
	private Integer gnumDisplayOrder;

	@Column(name = "gnum_seat_id")
	private Long gnumSeatId;

	@Column(name = "gdt_entry_date")
	private Timestamp gdtEntryDate;

	@Column(name = "gstr_url", length = 200)
	private String gstrUrl;

	@Column(name = "gnum_isvalid")
	private Integer gnumIsValid;

	@Column(name = "gnum_hl7_code")
	private Long gnumHl7Code;

	@Column(name = "gnum_isportal", nullable = false)
	private Integer gnumIsPortal;

	@Column(name = "gnum_menu_position")
	private Integer gnumMenuPosition;

	@Column(name = "gstr_js_function_name", length = 20)
	private String gstrJsFunctionName;

	@Column(name = "gnum_application_type")
	private Integer gnumApplicationType;

	@Column(name = "gnum_module_id")
	private Integer gnumModuleId;

	@Column(name = "gstr_image_class")
	private String gstrImageClass;

}
