package com.twd.SpringSecurityJWT.entity.master;
// Generated 1 Oct, 2018 4:11:17 PM by Hibernate Tools 5.2.3.Final

import java.io.Serializable;
import java.sql.Timestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import lombok.Data;

/**
 * UmmtUserMst generated by hbm2java
 */
@Data
@Entity
@Table(name = "gblt_nationality_mst", schema = "ahism")
@IdClass(GbltNationalityPKMst.class)
public class GbltNationalityMst implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "gnum_nationality_code", precision = 3, nullable = false)
	private Integer gnumNationalityCode;

	@Column(name = "gstr_nationality_name", length = 100, nullable = false, unique = true)
	private String gstrNationalityName;

	@Column(name = "gstr_country_code", length = 3, nullable = false, unique = true)
	private String gstrCountryCode;

	@Column(name = "gnum_seat_id", precision = 5, nullable = false)
	private Integer gnumSeatId;

	@Column(name = "gdt_entry", nullable = false)
	private Timestamp gdtEntry;

	@Column(name = "gnum_isvalid", precision = 1, nullable = false)
	private Integer gnumIsValid;

	@Column(name = "str_remarks", length = 50)
	private String strRemarks;

}
